# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Angeloni
email: chris.angeloni@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chris Angeloni - 2020.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "//chris-angeloni.github.io" # the base hostname & protocol for your site
github:  chris-angeloni
googlescholar: "https://scholar.google.com/citations?user=Z0eqlVUAAAAJ&hl=en"
instagram: chris.angeloni
twitter:
avatar: "https://avatars3.githubusercontent.com/u/3865975?v=4"
bio: "PhD Student studying auditory neuroscience. I also like making bikes, beer and art."


# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "art"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]
